Gatekeeper: Don't cache luaL_get_ctypeid() return
The error message we got LUA: dyn_cfg: ./lua/dylib.lua:88:
'short' has no member named 'addr'! when trying to send the
lua/example_of_dynamic_config_request.lua script multiple times
to Gatekeeper.

This is because each time we will create a new lua state for a
client connection. However, the lua state won't execute luaL_get_ctypeid()
because we declared "static bool assigned_type_xxx = false;" as a static
variable. That is, after the first time calling luaL_get_ctypeid() on the
corresponding type, the later lua states created dynamically won't have
a chance to get its type correctly.